server:
  port: 8050

spring:
  application:
    name: jt-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

logging:
  level:
    root: INFO

zuul:
  routes:
    app-a:
      path: /user/**
      serviceId: consumer-hystrix